- hosts: localhost
  tasks:
  - name: validate the change set
    inprod:
     host: 'blue.inprod.cloud'
     action: 'validate'
     username: 'milos'
     password: 'xx'
     changeset_id: 125
  - name: execute a changeset based on its Id
    inprod:
     host: 'blue.inprod.cloud'
     action: 'execute'
     username: 'milos'
     password: 'xx'
     changeset_id: 125
  - name: execute a changeset stored as JSON file
    inprod:
     host: 'blue.inprod.cloud'
     action: 'execute_json'
     username: 'milos'
     password: 'xx'
     file_path: '/Your Directory Path/execute.json'
